samples/Metrics/README.md
The project name was incorrect.
Also, I had to run `dotnet workload restore` to make the sample work, which the README doesn't mention. Maybe worth fixing too?
/cc @JamesNK
=> Fix Metrics README

samples/AspireWithNode/AspireWithNode.AppHost/NodeAppAddPortLifecycleHook.cs
This pull request addresses a typographical error in the codebase. The change involves correcting the spelling from `envAnnoation` to `envAnnotation` for clarity.
Fixed typo in AspireWithNode\AspireWithNode.AppHost\NodeAppAddPortLifecycleHook.cs
- Before: `envAnnoation`
- After: `envAnnotation`
=> Correct typo: `envAnnoation` to `envAnnotation`

samples/eShopLite/eShopLite.Frontend/Components/Cart.razor
Tweak to not attempt to call the checkout basket service if the call to get the basket returned null (meaning there's no current user basket).
I'll manually port this to the version of eShopLite in the main repo too.
Fixes #36
=> eShopLite: Don't checkout if there's no user basket

samples/AspireWithDapr/README.md
Resolves https://github.com/dotnet/aspire-samples/issues/65
=> Update Dapr README to call out dapr init

samples/Metrics/grafana/dashboards/aspnetcore-endpoint.json, samples/Metrics/grafana/dashboards/aspnetcore.json
Allow the metric dashboards to auto refresh.
Makes it easier to follow traffic when the auto fetch is activated in the blazor project.
=> Set dashboards refresh rate

samples/AspireWithJavaScript/AspireJavaScript.Angular/src/app/app.config.ts
This PR updates the JavaScript Angular example to its newest API.
The `HttpClientModule` will soon be deprecated, and later on removed.
@IEvangelist I was allowed to ping you 😉
I'll also update the docs at https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs next
=> refactor(angular): use provideHttpClient

samples/StandaloneDashboard/ConsoleApp/ConsoleApp.csproj, samples/StandaloneDashboard/ConsoleApp/Program.cs, samples/StandaloneDashboard/ConsoleApp/Properties/launchSettings.json, samples/StandaloneDashboard/ConsoleApp/appsettings.Development.json, samples/StandaloneDashboard/ConsoleApp/appsettings.json, samples/StandaloneDashboard/README.md
* Provide ability to disable OTLP export through configuration.
* Discuss configuration in the readme.
* General readme improvements.
Readme preview: https://github.com/dotnet/aspire-samples/blob/jamesnk/standalone-sample-configuration/samples/StandaloneDashboard/README.md
=> Add configuration of OTLP export endpoint to standalone dashboard sample and improve readme

samples/AspireWithJavaScript/AspireJavaScript.Angular/src/app/app.component.ts
Fixed a syntax issue where the previous code tried to pass an observer to the [`subscribe`](https://rxjs.dev/api/index/class/Observable#subscribe) method but passed an anonymous function instead. This caused the curly braces to become the body of the function and `next` and `error` to become labels.
=> Fixed subscribe call in angular sample

Directory.Packages.props
Pick up the otel CVE fix, plus update others since dependabot is struggling right now.
Used `dotnet outdated -vl Major -u for.dependabot.only.sln` (installed from https://github.com/dotnet-outdated/dotnet-outdated?tab=readme-ov-file#installation)
=> update nuget packages

.github/dependabot.yml
The NPM graphs are so large that we're going to get PR's like https://github.com/dotnet/aspire-samples/pull/229 almost daily. Change NPM to weekly.
=> change to check NPM for updates only weekly

tests/SamplesIntegrationTests/AppHostTests.cs, tests/SamplesIntegrationTests/Infrastructure/DistributedApplicationExtensions.cs, tests/SamplesIntegrationTests/Infrastructure/DistributedApplicationTestFactory.cs, tests/SamplesIntegrationTests/Infrastructure/LoggerLogStore.cs, tests/SamplesIntegrationTests/Infrastructure/PasswordGenerator.cs, tests/SamplesIntegrationTests/Infrastructure/ResourceExtensions.cs, tests/SamplesIntegrationTests/Infrastructure/ResourceLogStore.cs, tests/SamplesIntegrationTests/Infrastructure/ResourceWatcher.cs, tests/SamplesIntegrationTests/Infrastructure/StoredLogsLogger.cs, tests/SamplesIntegrationTests/Infrastructure/StoredLogsLoggerProvider.cs, tests/SamplesIntegrationTests/Infrastructure/XUnitExtensions.cs, tests/SamplesIntegrationTests/Infrastructure/XUnitLogger.cs, tests/SamplesIntegrationTests/Infrastructure/XUnitLoggerProvider.cs, tests/SamplesIntegrationTests/Infrastructure/XUnitTextWriter.cs, tests/SamplesIntegrationTests/SamplesIntegrationTests.csproj
Would appreciate your eyes @davidfowl @radical @ReubenBond 
The DatabaseMigrations sample test was flakey as the migrations project is just a console app so has no healthcheck endpoint that can be monitored before trying to call the actual app endpoint, so it would sometimes fail because the retries for the app endpoint would get exhausted before the migration had finished. Now, the test can wait for a specific resource to enter a specific state before continuing, which I use to wait for the migration app to exit before hitting the actual app endpoints.
=> Increase test HttpClient retries & optionally wait for resources to transition to target state

samples/DatabaseMigrations/DatabaseMigrations.ApiModel/DatabaseMigrations.ApiModel.csproj, samples/DatabaseMigrations/DatabaseMigrations.ApiModel/MyDb1Context.cs, samples/DatabaseMigrations/DatabaseMigrations.ApiService/Program.cs, samples/DatabaseMigrations/DatabaseMigrations.MigrationService/DatabaseMigrations.MigrationService.csproj, samples/DatabaseMigrations/DatabaseMigrations.MigrationService/Migrations/20240216140519_InitialCreate.Designer.cs, samples/DatabaseMigrations/DatabaseMigrations.MigrationService/Migrations/20240216140519_InitialCreate.cs, samples/DatabaseMigrations/DatabaseMigrations.MigrationService/Migrations/MyDb1ContextModelSnapshot.cs, samples/DatabaseMigrations/DatabaseMigrations.MigrationService/Program.cs, samples/DatabaseMigrations/README.md
This makes the `ApiService` compatible with NativeAOT and simplifies the tooling commands
=> Move migrations to DatabaseMigrations.MigrationService

.config/PoliCheckExclusions.xml, build/azure-pipelines.yml
* Get policheck clean by excluding angular.min.js, which we don't control.
* Get eslint clean by excluding jquery and angular.
I need to test this by running a pipeline, before merging.
=> Get more linter clean

samples/DatabaseContainers/DatabaseContainers.AppHost/sqlserverconfig/configure-db.sh
.. because the path `/opt/mssql-tools/bin/sqlcmd`
changed to `/opt/mssql-tools18/bin/sqlcmd`. And this is being used in
`samples/DatabaseContainers/DatabaseContainers.AppHost/sqlserverconfig/configure-db.sh`.
https://github.com/microsoft/mssql-docker/issues/892
Also, adds `-C` to trust the server certificate (see https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16&tabs=go%2Cwindows&pivots=cs1-bash#-c).
=> Workaround sqlserver 2022-latest latest image failing

samples/AspireWithAzureFunctions/ImageGallery.AppHost/Program.cs, samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/Components/Pages/Home.razor.cs, samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/ImageUrl.cs, samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/Program.cs, samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs, samples/AspireWithAzureFunctions/ImageGallery.Functions/ImageGallery.Functions.csproj, samples/AspireWithAzureFunctions/ImageGallery.Functions/ThumbnailGenerator.cs, tests/SamplesIntegrationTests/AppHostTests.cs, tests/SamplesIntegrationTests/Infrastructure/DistributedApplicationExtensions.cs
This PR fixes up a couple of issues with the Azure Functions sample that make it unpublishable:
- Enable external HTTP access on the Blazor front-end resource
- Configure the appropriate roles to support Blob triggers on the Azure Functions host
- Allow anonymous access to blobs in the storage account to support UI display in the Blazor front-end
- Reference `SkiaSharp.NativeAssets.Linux.NoDependencies` package to support running SkiaSharp in Linux containers on ACA
=> Fix up Azure Functions sample for publishing

samples/ContainerBuild/ContainerBuild.AppHost/Program.cs, samples/ContainerBuild/ContainerBuild.AppHost/appsettings.Development.json, samples/ContainerBuild/ContainerBuild.AppHost/appsettings.json, samples/ContainerBuild/ginapp/ginapp.go
- Ensure trusted proxies is explicitly configured in gin app
- Add workaround for azd not supporting default parameter values
- Mark HTTP endpoints on gin app as external
- Run gin app in release mode when published or in production
Contributes to #452
=> Improve the deployability of the container build sample

samples/AspireWithNode/AspireWithNode.AppHost/AspireWithNode.AppHost.csproj, samples/AspireWithNode/AspireWithNode.AppHost/NodeHostingExtensions.cs, samples/AspireWithNode/AspireWithNode.AppHost/Program.cs, samples/AspireWithNode/NodeFrontend/app.js, samples/Shared/DevCertHostingExtensions.cs
Updates the Node.js sample to use the ASP.NET Core HTTPS dev certificate.
@mitchdenny @davidfowl you might want to take a look at the use of eventing here. I had some issues trying to achieve the method layering with anything other than the `BeforeStartEvent` but @davidfowl pointed out that work in that event blocks the dashboard from starting which is unfortunate but ultimately probably not a huge concern in this case. Specifically the need here is to do work (exporting the dev cert) that if successful results in changes to the resource (adding env vars, endpoints, bind mounts, and maybe more env vars that reference the added endpoints), and has access to a resource logger during that work.
=> Update the Node sample to use the dev cert

samples/AspireWithPython/AspireWithPython.AppHost/Program.cs, samples/AspireWithPython/InstrumentedPythonProject/Dockerfile, samples/AspireWithPython/InstrumentedPythonProject/app.py, samples/AspireWithPython/InstrumentedPythonProject/gunicorn_config.py, samples/AspireWithPython/InstrumentedPythonProject/requirements.txt
- Add a Dockerfile
- Configure published app to use gunicorn WSGI server
- Mark Python app external
- Rename main.py to app.py (more inline with online tutorials)
App now deploys to ACA using azd successfully and emits OTel data:
Fixes #530
=> Make python app sample deployable

samples/AspireShop/AspireShop.AppHost/Program.cs
Postgres doesn't work in ACA when using a data volume so only add it when in run mode.
Fixes #433
=> Make AspireShop deployable

samples/AspireShop/AspireShop.CatalogDb/CatalogDbContext.cs, samples/AspireShop/AspireShop.CatalogService/CatalogApi.cs, samples/AspireShop/AspireShop.Frontend/Services/CatalogServiceClient.cs
Fixed the keyset pagination implementation ([source doc for reference](https://use-the-index-luke.com/no-offset)). In short, you have to order the query differently depending on whether you're navigating forward or backward.
Also tweaked CatalogAPI shape for better OpenAPI/Swagger experience.
https://github.com/user-attachments/assets/d0af0195-0f4a-4979-8e4a-4fdee0871eae
Fixes #322
=> Fixed AspireShop paging

samples/OrleansVoting/OrleansVoting.AppHost/Program.cs
After testing to make sure #148 is fixed with the latest `azd` and Aspire 9 bits, this fix was needed for exposing the UX via public ingress.
=> configured public ingress

samples/HealthChecksUI/HealthChecksUI.AppHost/HealthChecksUIResource.cs, samples/HealthChecksUI/HealthChecksUI.AppHost/Program.cs, samples/HealthChecksUI/HealthChecksUI.AppHost/aspire-manifest.json
Removes workarounds in the HealthChecksUI sample that should no longer be required now that dotnet/aspire#3786 and dotnet/aspire#3749 are fixed.
~NOTE: I'm currently deploying the sample via `azd` to ensure it still works. Will update here to confirm outcome once done.~
~OK so seems there's a regression from this change. I'll investigate:~
LOL it came good after a few seconds 😄 
`azd up` output:
```
Packaging services (azd package)
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.
Subscription: ****
Location: ****
You can view detailed progress in the Azure Portal:
*****
(✓) Done: Container Registry: acrrfuiqiqdyuxji (9.938s)
(✓) Done: Log Analytics workspace: law-rfuiqiqdyuxji (18.178s)
(✓) Done: Container Apps Environment: cae-rfuiqiqdyuxji …
```
=> Remove workarounds in HealthChecksUI sample

build/azure-pipelines.yml
Builds have been failing because the 9.0.100 SDK isn't installed on the build machines - this should fix that going forward
=> Install .NET SDK in CI

samples/AspireShop/AspireShop.AppHost/Program.cs, samples/AspireShop/AspireShop.AppHost/ResourceBuilderExtensions.cs
Changes the AspireShop sample so that the `WithHttpCommand` works by default against endpoints named "https" or "http".
Fixes #677
=> AspireShop: Simplify WithHttpCommand

.devcontainer/devcontainer.json, README.md
Fixes #739
Add devcontainer configuration to the repository to enable running samples via Codespaces.
* **Add `.devcontainer/devcontainer.json`**:
- Set the `name` to ".NET Aspire Samples".
- Use the `image` "mcr.microsoft.com/devcontainers/dotnet:dev-9.0-bookworm".
- Add necessary `features` for the devcontainer.
- Add `customizations` for VS Code extensions and settings.
- Set `onCreateCommand` to "dotnet restore".
- Set `postStartCommand` to "dotnet dev-certs https --trust".
- Configure `remoteEnv` for the PATH.
* **Update `README.md`**:
- Add a section about using devcontainer and Codespaces to run the samples.
- Provide instructions on how to set up and use the devcontainer.
- Include steps for setting up Devcontainer and using GitHub Codespaces.
---
For more details, open the …
=> Add devcontainer to this repo

samples/AspireWithPython/InstrumentedPythonProject/Dockerfile
This supersedes an internal PR opened by dependabot..
FYI: @DamianEdwards
=> Bump python from 3.12.5-slim to 3.12.9-slim
