CODE_OF_CONDUCT.md, README.md
We used the wrong one -- should be the Foundation one.
=> correct codeofconduct.md

samples/eShopLite/deploy.ps1, samples/eShopLite/deploy.sh
1. Line 42 "-" a hypen is missing
=> Update deploy.ps1- Line 42 "-" a hypen is missing

README.md
=> Add CI status shield to README

.gitignore
Just extra patterns to be ignored on MacOSX
=> macosx gitignore

samples/ClientAppsIntegration/ClientAppsIntegration.AppHost/Program.cs
=> Exclude client app projects from publish manifest

samples/Metrics/MetricsApp.Client/MetricsApp.Client.csproj
Mitigates https://github.com/dotnet/runtime/issues/101154
=> Disable WasmEnableWebcil

samples/AspireWithJavaScript/AspireJavaScript.Angular/Dockerfile, samples/AspireWithJavaScript/AspireJavaScript.Angular/package.json, samples/AspireWithJavaScript/AspireJavaScript.React/Dockerfile, samples/AspireWithJavaScript/AspireJavaScript.Vue/Dockerfile, samples/AspireWithJavaScript/AspireJavaScript.Vue/package-lock.json, samples/AspireWithJavaScript/AspireJavaScript.Vue/package.json, samples/AspireWithNode/NodeFrontend/Dockerfile, samples/AspireWithNode/NodeFrontend/package.json
- Ensure Dockerfiles reference the "node" image use the major version tag so they float to latest patch level
- Update package.json files to specify latest Node.js version
=> Bump node min versions

samples/AspireShop/AspireShop.BasketService/AspireShop.BasketService.csproj, samples/AspireShop/AspireShop.CatalogDbManager/AspireShop.CatalogDbManager.csproj, samples/AspireShop/AspireShop.CatalogService/AspireShop.CatalogService.csproj, samples/AspireShop/AspireShop.Frontend/AspireShop.Frontend.csproj, samples/AspireShop/AspireShop.ServiceDefaults/AspireShop.ServiceDefaults.csproj, samples/AspireWithDapr/AspireWithDapr.ServiceDefaults/AspireWithDapr.ServiceDefaults.csproj, samples/AspireWithJavaScript/AspireJavaScript.MinimalApi/AspireJavaScript.MinimalApi.csproj, samples/AspireWithJavaScript/AspireJavaScript.ServiceDefaults/AspireJavaScript.ServiceDefaults.csproj, samples/AspireWithNode/AspireWithNode.ServiceDefaults/AspireWithNode.ServiceDefaults.csproj, samples/ClientAppsIntegration/ClientAppsIntegration.AppDefaults/ClientAppsIntegration.AppDefaults.csproj, samples/ClientAppsIntegration/ClientAppsIntegration.ServiceDefaults/ClientAppsIntegration.ServiceDefaults.csproj, samples/DatabaseContainers/DatabaseContainers.ApiService/DatabaseContainers.ApiService.csproj, samples/DatabaseContainers/DatabaseContainers.ServiceDefaults/DatabaseContainers.ServiceDefaults.csproj, samples/DatabaseMigrations/DatabaseMigrations.ApiModel/DatabaseMigrations.ApiModel.csproj, samples/DatabaseMigrations/DatabaseMigrations.MigrationService/DatabaseMigrations.MigrationService.csproj, samples/DatabaseMigrations/DatabaseMigrations.ServiceDefaults/DatabaseMigrations.ServiceDefaults.csproj, samples/Metrics/MetricsApp/MetricsApp.csproj, samples/Metrics/ServiceDefaults/ServiceDefaults.csproj, samples/OrleansVoting/OrleansVoting.ServiceDefaults/OrleansVoting.ServiceDefaults.csproj, samples/StandaloneDashboard/ConsoleApp/ConsoleApp.csproj, samples/VolumeMount/VolumeMount.ServiceDefaults/VolumeMount.ServiceDefaults.csproj
```
dotnet tool install --global dotnet-outdated-tool
dotnet outdated -vl Major -u
```
(this picked up for.dependabot.only.sln, all samples need to be in there.)
=> update dependency versions

build/azure-pipelines-pr.yml
Related to https://github.com/dotnet/aspire-samples/issues/196
=> Create 1ESPT azdo pipeline

.github/dependabot.yml
=> Update Orleans packages together

tests/SamplesIntegrationTests/AppHostTests.cs
#362 made this change mistakenly. Reverting that change.
=> Revert unnecessary edit from 8.1 update

samples/OrleansVoting/OrleansVoting.Service/Program.cs
The Silo port and Gateway port are already injected as Environmental Variables
```
Orleans__Endpoints__GatewayPort
Orleans__Endpoints__SiloPort
```
=> Utilize injected ports

samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/ImageUrl.cs
This is a better way to do the replacement that doesn't assume the length is something that can be allocated on the heap.
=> Use string.Create and remove stackalloc

samples/AspireWithAzureFunctions/ImageGallery.AppHost/Program.cs, tests/SamplesIntegrationTests/SamplesIntegrationTests.csproj
Also use the correct version for Aspire.Hosting.Azure
=> Fix provisioning code to find the right StorageAccount.

samples/Metrics/MetricsApp.AppHost/OpenTelemetryCollector/OpenTelemetryCollectorLifecycleHook.cs
Feedback from https://github.com/dotnet/aspire-samples/pull/606#pullrequestreview-2484170892
=> Update OTEL collector to forward non-project resources

samples/AspireWithJavaScript/AspireJavaScript.Angular/package-lock.json
Fixes dependabot warning for vulnerable dependency.
cc: @DamianEdwards
=> Update npm dependencies to address security warning due to transitive dependency.

.github/workflows/ci.yml
given https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
pin our github actions using https://github.com/mheap/pin-github-action and spot check the SHAs.
=> pin actions

samples/AspireWithAzureFunctions/ImageGallery.AppHost/ImageGallery.AppHost.csproj, samples/AspireWithAzureFunctions/ImageGallery.AppHost/Program.cs
=> Updated the functions sample to use WithRoleAssignment

global.json, samples/Metrics/grafana/dashboards/aspnetcore-endpoint.json, samples/Metrics/grafana/dashboards/aspnetcore.json
Testing https://github.com/dotnet/aspire/pull/7021
=> Update metrics dashboard from PR

samples/AspireWithPython/InstrumentedPythonProject/Dockerfile
=> Update Python base image version in Dockerfile
